name: 'fix-whitespace-action'
description: 'Run fix-whitespace  on your repo'
author: 'Andreas Abel'
inputs:
  version:
    description: 'Version of fix-whitespace program'
    required: true
    default: '0.0.10'
  configfile:
    description: 'Name of fix-whitespace configuration file'
    required: true
    default: 'fix-whitespace.yaml'
  fix:
    description: 'Fix whitespace violations?'
    required: true
    default: false
  # allow-tabs:
  #   description: 'Allow tabs or convert to given column spacing, if'
  #   required: false

runs:
  using: 'composite'
  steps:

    - name: "Install fix-whitespace"
      shell: bash
      run: |
        # Download binary
        if   [[ "${{ runner.os }}" == "Linux"   ]]; then
          EXT="-linux.binary"
        elif [[ "${{ runner.os }}" == "macOS"   ]]; then
          EXT="-mac.binary"
        elif [[ "${{ runner.os }}" == "Windows" ]]; then
          EXT=".exe"
        fi
        SRC="fix-whitespace-${{ inputs.version }}${EXT}"
        wget "https://github.com/agda/fix-whitespace/releases/download/v${{ inputs.version }}/${SRC}"

        # Put binary as fix-whitespace to ~/.local/bin and put that into the PATH.
        DIR="$HOME/.local/bin"
        chmod +x "${SRC}"
        mkdir -p "${DIR}"
        mv "${SRC}" "${DIR}/fix-whitespace"
        echo "${DIR}" >> "${GITHUB_PATH}"

    - name: "Run fix-whitespace at the root"
      shell: bash
      run: |
        if [[ "${{ inputs.fix }}" != "true" ]]; then
          MODE="--check"
        fi
        fix-whitespace --config=${{ inputs. configfile}} ${MODE}
