name: Check whitespace
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - uses: andreasabel/fix-whitespace-action@master
      with:
        verbose: true
      ## OPTIONAL
      #   version: 0.1
