name: Check whitespace
on:
  push:
    branches:
      - master
      - ci*
  pull_request:
    branches:
      - master
      - ci*
  workflow_dispatch:

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: andreasabel/fix-whitespace-action@master
      ## OPTIONAL
      # with:
      #   version: 0.0.11
